routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'Admin\HomeController@index')->name('home');
    Route::get('/menu', 'Admin\Menu\QuestsController@index')->name('menu')->middleware('auth');
    Route::get('/menu-tests/{type}', 'Admin\Menu\TestsController@index')->name('menu.tests');
    Route::resource('/themes', 'Admin\ThemesController');
    Route::resource('/quests', 'Admin\QuestsController')->middleware('auth');
    Route::get('/common_menu', 'Admin\CommonController@menu')->name('common.menu');
    Route::get('/tests', 'Admin\TestController@index')->name('tests')->middleware('auth');
    Route::delete('/tests/delete/{test}', 'Admin\TestController@delete')->name('admin.destroy');
    Route::post('/positive/{theme}/{id}/{is_oral}', 'Admin\TestController@positive')->name('positive');
    Route::post('/negative/{theme}/{id}/{is_oral}', 'Admin\TestController@negative')->name('negative');
    Route::get('/counters', 'Admin\CountersController@index')->name('counters');
    Route::post('/counters/to_zero/{id}', 'Admin\CountersController@zero')->name('counters.to.zero');
    Route::get('/search/', 'Admin\QuestsController@search')->name('quests.search');
    Route::get('/common_index', 'Admin\CommonController@index')->name('common.index');
    Route::get('/print-menu', 'Admin\Menu\PrintController@menu')->name('print.menu');

    Route::get('/curriculum', 'Admin\Menu\CurriculumController@main')->name('curriculum.menu');
    Route::post('/curriculum-store', 'Admin\Menu\CurriculumController@store')->name('curriculum.store');
    Route::get('/school-menu', 'Admin\SchoolController@menu')->name('school.menu');
    Route::get('/school-question', 'Admin\SchoolController@question')->name('school.question');
    Route::post('/school-positive/{question}', 'Admin\SchoolController@positive')->name('school.positive');
    Route::post('/school-negative/{question}', 'Admin\SchoolController@negative')->name('school.negative');
    Route::delete('/school-delete/{question}', 'Admin\SchoolController@delete')->name('school.delete');

    Route::get('print-page', 'Admin\PrintPageController@index')->name('print.page');
    Route::get('/large-intervew', 'Admin\LargeInterviewController@menu')->name('large.interview.menu');
    Route::get('/large-intervew-quest', 'Admin\LargeInterviewController@quest')->name('large.interview.quest');
});
Route::get('/mysql','Redirects\MysqlController@index');

app/Models/Theme.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Theme extends Model
{
    /**
     * Подключен к этой таблице
     *
     * @var string
     */
    protected $table = 'themes';

    protected $fillable = ['in_school'];

    /**
     * Выдает все темы в виде массива
     *
     * @param Request $request
     * @return array
     */
    public function getAllThemesByArray()
    {
        $themes = $this->all();

        $result = [];
        foreach($themes as $theme){
            $result[$theme->id] = $theme->title;
        }

        return $result;
    }

}

app/Http/Controllers/Admin/ThemesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Theme;
use Illuminate\Http\Request;

/**
 * Class ThemesController
 * @package App\Http\Controllers\Admin
 */
class ThemesController extends BaseController
{
    /**
     * Размер пагинации
     *
     * @var int
     */
    private $paginate = 25;

    /**
     * Это экземпляр класса Theme
     *
     * @var Theme
     */
    private $theme;

    public function __construct(Theme $theme)
    {
        $this->theme = $theme;
    }

    /**
     * Общий список новых тем
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $themes = $this->theme
            ->paginate($this->paginate);

        return view('admin.themes.index', compact('themes'));
    }

    /**
     * Форма создания новой темы
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.themes.create');
    }

    /**
     * Сохранений новой темы
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $theme = $this->theme;
        $theme->title = $request->title;
        $theme->enable = (isset($request->enabled)) ? true : false;
        $theme->save();

        return redirect(route('themes.index'))
            ->with('message', 'Новая тема ' . $theme->title . ' успешно добавленa');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Форма редактирования существующей темы
     *
     * @param Theme $theme
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Theme $theme, Request $request)
    {
        return view('admin.themes.edit', compact('theme'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Theme $theme, Request $request)
    {
        $theme->title = $request->title;
        $theme->enable = (isset($request->enabled)) ? true : false;
        $theme->save();

        return redirect(route('themes.index'))
            ->with('message', 'Тема ' . $theme->title . ' успешно обновлена');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Theme $theme)
    {
        $theme->delete();

        return redirect(route('themes.index'))
            ->with('message', 'Тема ' . $theme->title . ' удалена');
    }
}

resources/views/admin/themes/_form.blade.php
<form
    method="POST"
    action="{{ isset($theme) ? route('themes.update', $theme) : route('themes.store') }}"
    enctype="multipart/form-data"
>
    @csrf
    @if (isset($theme))
        @method('PATCH')
    @endif
    <div class="form-group">
        <label for="theme">Новая тема</label>
        <input  type="text"
                class="form-control"
                id="title"
                name="title"
                value="{{ isset($theme) ? $theme->title : null }}"
        >
        <small class="form-text text-muted">Название темы</small>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-enabled" id="enabled" name="enabled"
               @if(isset($theme) && $theme->enable)
               checked
            @endif
        >
        <label class="form-enabled" for="enabled">Включить</label>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>

resources/views/admin/themes/create.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.themes._form')
@endsection

resources/views/admin/themes/edit.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.themes._form')
@endsection

resources/views/admin/themes/index.blade.php
@php($message = Session::get('message'))
@extends('layouts.app')
@section('content')
    @if(isset($message))
        <div class="alert alert-danger" role="alert">
            {{ $message }}
        </div>
    @endif
    <a href="{{ route('themes.create') }}" class="btn btn-primary float-right add-note">Добавить</a>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Название темы</th>
            <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($themes as $theme)
        <tr>
            <td>{{ $theme->id }}</td>
            <td>{{ $theme->title }}</td>
            <td>{{ $theme->enable ? 'Включен' : '' }}</td>
            <td>
                <a href="{{route('themes.edit', $theme)}}">
                    <i class="material-icons">edit</i>
                </a>
            </td>
            <td>
                <form
                    method="POST"
                    action="{{route('themes.destroy', $theme)}}"
                >
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="material-icons">
                        <i class="material-icons">clear</i>
                    </button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
    {{ $themes->links() }}
@endsection