routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'Admin\HomeController@index')->name('home');
    Route::get('/menu', 'Admin\Menu\QuestsController@index')->name('menu')->middleware('auth');
    Route::get('/menu-tests/{type}', 'Admin\Menu\TestsController@index')->name('menu.tests');
    Route::resource('/themes', 'Admin\ThemesController');
    Route::resource('/quests', 'Admin\QuestsController')->middleware('auth');
    Route::get('/common_menu', 'Admin\CommonController@menu')->name('common.menu');
    Route::get('/tests', 'Admin\TestController@index')->name('tests')->middleware('auth');
    Route::delete('/tests/delete/{test}', 'Admin\TestController@delete')->name('admin.destroy');
    Route::post('/positive/{theme}/{id}/{is_oral}', 'Admin\TestController@positive')->name('positive');
    Route::post('/negative/{theme}/{id}/{is_oral}', 'Admin\TestController@negative')->name('negative');
    Route::get('/counters', 'Admin\CountersController@index')->name('counters');
    Route::post('/counters/to_zero/{id}', 'Admin\CountersController@zero')->name('counters.to.zero');
    Route::get('/search/', 'Admin\QuestsController@search')->name('quests.search');
    Route::get('/common_index', 'Admin\CommonController@index')->name('common.index');
    Route::get('/print-menu', 'Admin\Menu\PrintController@menu')->name('print.menu');

    Route::get('/curriculum', 'Admin\Menu\CurriculumController@main')->name('curriculum.menu');
    Route::post('/curriculum-store', 'Admin\Menu\CurriculumController@store')->name('curriculum.store');
    Route::get('/school-menu', 'Admin\SchoolController@menu')->name('school.menu');
    Route::get('/school-question', 'Admin\SchoolController@question')->name('school.question');
    Route::post('/school-positive/{question}', 'Admin\SchoolController@positive')->name('school.positive');
    Route::post('/school-negative/{question}', 'Admin\SchoolController@negative')->name('school.negative');
    Route::delete('/school-delete/{question}', 'Admin\SchoolController@delete')->name('school.delete');

    Route::get('print-page', 'Admin\PrintPageController@index')->name('print.page');
    Route::get('/large-intervew', 'Admin\LargeInterviewController@menu')->name('large.interview.menu');
    Route::get('/large-intervew-quest', 'Admin\LargeInterviewController@quest')->name('large.interview.quest');
});
Route::get('/mysql','Redirects\MysqlController@index');

app/Http/Controllers/Admin/Menu/CurriculumController.php
<?php

namespace App\Http\Controllers\Admin\Menu;

use App\Repositories\ThemeRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CurriculumController extends Controller
{
    private $themeRepository;

    public function __construct(ThemeRepository $themeRepository)
    {
        $this->themeRepository = $themeRepository;
    }

    public function main()
    {
        return view('menu.curriculum', [
            'themes' => $this->themeRepository->getAllEnabledThemes(),
            'format' => $this->themeRepository->getFormatToLearn(),
        ]);
    }

    public function store(Request $request)
    {
        $this->themeRepository->storeFormatToLearn($request);
        $this->themeRepository->storeThemeInSchool($request);

        return view('menu.curriculum_store');
    }
}

app/Http/Controllers/Admin/Menu/PrintController.php
<?php

namespace App\Http\Controllers\Admin\Menu;

use App\Helpers\ThemeHelper;
use App\Http\Controllers\Controller;

class PrintController extends Controller
{
    private const WRITTEN_TESTS = 2;

    public function menu()
    {
        return view('menu.print', [
            'themes' => ThemeHelper::list(self::WRITTEN_TESTS),
            'type'   => self::WRITTEN_TESTS,
        ]);
    }
}

app/Http/Controllers/Admin/Menu/QuestsController.php
<?php

namespace App\Http\Controllers\Admin\Menu;

use App\Models\Theme;
use App\Http\Controllers\Admin\BaseController;

/**
 * Class QuestsController
 * @package App\Http\Controllers\Admin\Menu
 */
class QuestsController extends BaseController
{
    /**
     * Это экземпляр Theme
     *
     * @var Theme
     */
    private $theme;

    public function __construct(Theme $theme)
    {
        $this->theme = $theme;
    }

    /**
     * Меню для выбора темы вопросов
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('menu.quests', [
            'themes' => $this->theme->get(),
        ]);
    }
}

app/Http/Controllers/Admin/Menu/TestsController.php
<?php

namespace App\Http\Controllers\Admin\Menu;

use App\Helpers\ThemeHelper;
use App\Http\Controllers\Admin\BaseController;

/**
 * Class TestsController
 * @package App\Http\Controllers\Admin\Menu
 */
class TestsController extends BaseController
{
    /**
     *  Меню для выбора темы вопросов
     * @param $type
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index($type)
    {
        return view('menu.tests', [
            'themes' => ThemeHelper::list($type),
            'type'   => $type,
        ]);
    }
}

resources/views/menu/curriculum.blade.php
@extends('layouts.app')
@section('content')
    <div class="btn-group-vertical">
        <h3>Формат обучения:</h3>
        <form method="post" action="{{ route('curriculum.store') }}">
            @csrf
            <div class="form-group">
                <div class="radio">
                    <label>
                        <input type="radio" name="format" id="optionsRadios1" value="written"
                               @if ($format === 'written')
                               checked
                            @endif
                        >
                        Письменная программа
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="format" id="optionsRadios2" value="oral"
                               @if ($format === 'oral')
                               checked
                            @endif
                        >
                        Устная программа
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="format" id="optionsRadios2" value="complex"
                               @if ($format === 'complex')
                               checked
                            @endif
                        >
                        Комплексная программа
                    </label>
                </div>
                <h3>Темы:</h3>
                @foreach($themes as $theme)
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="theme[]" value="{{ $theme->id }}"
                                   @if ($theme->in_school === true)
                                   checked
                                @endif
                            >
                            {{ $theme->title }}
                            @if ($theme->in_school === true)
                                checked
                            @endif
                        </label>
                    </div>
                @endforeach
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/menu/curriculum_store.blade.php
@extends('layouts.app')
@section('content')
    <div class="btn-group-vertical">
        <h3>Формат Установлен</h3>
    </div>
@endsection

resources/views/menu/print.blade.php
@extends('layouts.app')
@section('content')
    <div class="btn-group-vertical">
        <h3>Выбор тестов на печать</h3>
        @foreach($themes as $theme)
            @if($theme->enable)
                <a href="{{ route('print.page',['theme'=>$theme->id,'type'=>$type,]) }}" type="button" class="btn btn-secondary">
                    {{ $type == 1 ? 'Устный тест' : 'Письменный тест' }} - {{ $theme->title }}({{ $theme->quantity }})
                </a>
            @endif
        @endforeach

    </div>
@endsection

resources/views/menu/quests.blade.php
@extends('layouts.app')
@section('content')
    <div class="btn-group-vertical">
        @foreach($themes as $theme)
            @if($theme->enable)
                <a href="{{ route('quests.index',['theme'=>$theme->id,]) }}" type="button" class="btn btn-secondary">{{ $theme->title }}({{ $theme->id }})</a>
            @endif
        @endforeach
    </div>
@endsection

resources/views/menu/school_menu.blade.php
@extends('layouts.app')
@section('content')
    <div class="btn-group-vertical">
        <h3>Выбор класса:</h3>
        <form method="get" action="{{ route('school.question') }}">
            @csrf
            @for($i = 1; $i <= 14; $i++)
            <div class="form-group">
                <div class="radio">
                    <label>
                        <input type="radio" name="class" id="optionsRadios1" value="{{ $i }}">
                        {{ $i }} класс [{{ $counts[$i]}}]
                    </label>
                </div>
            </div>
            @endfor
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/menu/tests.blade.php
@extends('layouts.app')
@section('content')

    <div class="btn-group-vertical">
        @foreach($themes as $theme)
            @if($theme->enable)
                <a href="{{ route('tests',['theme'=>$theme->id,'type'=>$type,]) }}" type="button" class="btn btn-secondary">
    {{ $type == 1 ? 'Устный тест' : 'Письменный тест' }} - {{ $theme->title }}({{ $theme->quantity }})
                </a>
            @endif
        @endforeach
    </div>
@endsection