routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'Admin\HomeController@index')->name('home');
    Route::get('/menu', 'Admin\Menu\QuestsController@index')->name('menu')->middleware('auth');
    Route::get('/menu-tests/{type}', 'Admin\Menu\TestsController@index')->name('menu.tests');
    Route::resource('/themes', 'Admin\ThemesController');
    Route::resource('/quests', 'Admin\QuestsController')->middleware('auth');
    Route::get('/common_menu', 'Admin\CommonController@menu')->name('common.menu');
    Route::get('/tests', 'Admin\TestController@index')->name('tests')->middleware('auth');
    Route::delete('/tests/delete/{test}', 'Admin\TestController@delete')->name('admin.destroy');
    Route::post('/positive/{theme}/{id}/{is_oral}', 'Admin\TestController@positive')->name('positive');
    Route::post('/negative/{theme}/{id}/{is_oral}', 'Admin\TestController@negative')->name('negative');
    Route::get('/counters', 'Admin\CountersController@index')->name('counters');
    Route::post('/counters/to_zero/{id}', 'Admin\CountersController@zero')->name('counters.to.zero');
    Route::get('/search/', 'Admin\QuestsController@search')->name('quests.search');
    Route::get('/common_index', 'Admin\CommonController@index')->name('common.index');
    Route::get('/print-menu', 'Admin\Menu\PrintController@menu')->name('print.menu');

    Route::get('/curriculum', 'Admin\Menu\CurriculumController@main')->name('curriculum.menu');
    Route::post('/curriculum-store', 'Admin\Menu\CurriculumController@store')->name('curriculum.store');
    Route::get('/school-menu', 'Admin\SchoolController@menu')->name('school.menu');
    Route::get('/school-question', 'Admin\SchoolController@question')->name('school.question');
    Route::post('/school-positive/{question}', 'Admin\SchoolController@positive')->name('school.positive');
    Route::post('/school-negative/{question}', 'Admin\SchoolController@negative')->name('school.negative');
    Route::delete('/school-delete/{question}', 'Admin\SchoolController@delete')->name('school.delete');

    Route::get('print-page', 'Admin\PrintPageController@index')->name('print.page');
    Route::get('/large-intervew', 'Admin\LargeInterviewController@menu')->name('large.interview.menu');
    Route::get('/large-intervew-quest', 'Admin\LargeInterviewController@quest')->name('large.interview.quest');
});
Route::get('/mysql','Redirects\MysqlController@index');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    public function themes()
    {
        return $this->belongsTo('App\Models\Theme', 'theme', 'id');
    }
}

resources/views/admin/questions/_form.blade.php
<form
    method="POST"
    action="{{ isset($question) ? route('quests.update', $question) : route('quests.store') }}"
    enctype="multipart/form-data"
>
    @csrf
    @if (isset($question))
        @method('PATCH')
    @endif

    <div class="form-group">
        <label for="theme">Новый вопрос</label>
        <input  type="text"
                class="form-control"
                id="title"
                name="question"
                value="{{ isset($question) ? $question->question : null }}"
                required
        >
        <br>
        <select name="theme">
            @foreach ($allThemes as $theme)
                <li><option
                    @if((isset($request->theme) ? $request->theme : $question->theme)===$theme->id)
                        selected
                    @endif
                    value="{{ $theme->id }}"
                    >{{ $theme->title }}</option></li>
            @endforeach
        </select>
        <br>
        <small class="form-text text-muted">Текст вопроса</small>
    </div>

    <div class="form-group">
<textarea class="form-control"
          name="answer"
          id="exampleFormControlTextarea1"
          rows="6"
          required
>{{ isset($question) ? $question->answer : null }}</textarea>
        <small class="form-text text-muted">Ответ</small>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-enabled" id="is_oral" name="is_oral"
               @if(isset($question) && $question->is_oral)
               checked
            @endif
        >
        <label class="form-enabled" for="enabled">Устный ответ</label>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>

resources/views/admin/questions/create.blade.php
@extends('layouts.app')
@section('content')
    <form
        method="POST"
        action="{{ isset($question) ? route('quests.update', $question) : route('quests.store') }}"
        enctype="multipart/form-data"
    >
        @csrf
        @if (isset($question))
            @method('PATCH')
        @endif

        <div class="form-group">
            <label for="theme">Новый вопрос</label>
            <input  type="text"
                    class="form-control"
                    id="title"
                    name="question"
                    value="{{ isset($question) ? $question->question : null }}"
                    required
            >
            <br>
            <select name="theme">
                @foreach ($allThemes as $theme)
                    <li><option
                            @if($request->theme == $theme->id)
                            selected
                            @endif
                            value="{{ $theme->id }}"
                        >{{ $theme->title }}</option></li>
                @endforeach
            </select>
            <br>
            <small class="form-text text-muted">Текст вопроса</small>
        </div>

        <div class="form-group">
<textarea class="form-control"
          name="answer"
          id="exampleFormControlTextarea1"
          rows="6"
          required
>{{ isset($question) ? $question->answer : null }}</textarea>
            <small class="form-text text-muted">Ответ</small>
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-enabled" id="is_oral" name="is_oral"
                   @if(isset($question) && $question->is_oral)
                   checked
                @endif
            >
            <label class="form-enabled" for="enabled">Устный ответ</label>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
@endsection

resources/views/admin/questions/edit.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.questions._form')
@endsection

resources/views/admin/questions/index.blade.php
@php($message = Session::get('message'))
@extends('layouts.app')
@section('content')
    <h2>Тема: {{ $themeInfo->title }}</h2>
    @if(isset($message))
        <div class="alert alert-danger" role="alert">
            {{ $message }}
        </div>
    @endif
    <form method="GET" action="{{ route('quests.search', ['theme' => $theme,]) }}">
        <div class="form-group">
            <label for="exampleInputEmail1">Поиск по содержимому</label>
            <input type="search" class="form-control" id="searchInput" name="search">
            <input type="hidden" name="theme" value="{{ $theme }}">
        </div>
        <button type="submit" class="btn btn-primary">Найти</button>
    <a href="{{ route('quests.create', ['theme' => $theme,]) }}" class="btn btn-primary float-right add-note">Добавить</a>
    </form>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Вопрос</th>
            <th scope="col">Тип ответа</th>
            <th scope="col">Статус</th>
            <th scope="col">Обновлено</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($questions as $question)
            <tr>
                <td>{{ $question->id }}</td>
                <td>{{ $question->question }}</td>
                <td>{{ $question->is_oral ? 'Устный' : '' }}</td>
                <td>{{ $question->status }}</td>
                <td>{{ $question->updated_at }}</td>
                <td>
                    <a href="{{route('quests.edit', $question)}}">
                        <i class="material-icons">edit</i>
                    </a>
                </td>
                <td>
                    <form
                        method="POST"
                        action="{{route('quests.destroy', $question)}}"
                    >
                        <input type="hidden"
                               name="theme"
                               value="{{ $theme }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="material-icons">
                            <i class="material-icons">clear</i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $questions->appends(['theme' => $theme])->links() }}
@endsection